#server:
#    port: 8080
#    servlet:
#      context-path:demo

#默认配置
#spring:
#    datasource:
#        url: jdbc:mysql://localhost:3306/db_demo_project?useUnicode=true&characterEncoding=utf8
#        data-username: root
#        password: 123
#        driver-class-name: com.mysql.jdbc.Driver
#        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource

druid:
    url: jdbc:mysql://47.106.194.61:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: Hmlin5#
    driverClassName: com.mysql.jdbc.Driver

#bonecp:
#    jdbcUrl: jdbc:mysql://localhost:3306/db_demo_project?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
#    username: root
#    password: 123
#    driverClass: com.mysql.cj.jdbc.Driver

#加载Mybatis核心配置文件
mybatis:
    mapper-locations: classpath:mapper/*/*.xml
#    scanBasePackage: com.hmlin5.demo
#    type-aliases-package:   # 注意：对应实体类的路径

pagehelper:
    helperDialect: mysql
 #   offsetAsPageNum: true
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql

logging:
    level:
        com.hmlin5.demo: debug
spring:
    mvc:
        view:
            prefix: /pages/
            suffix: .html
        static-path-pattern: /**
    resources:
         static-locations: /META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}


#web:
#    upload-path: D:/upload/
#    resource-url: http://127.0.0.1:8080/

